version: "3.8"

services:
  api:
    build: ./backend
    container_name: analista_api
    volumes:
      - ./backend/app:/app/app
      - ./data:/var/abastece/dados
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: analista_web
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que o volume sobrescreva os pacotes instalados no container
    ports:
      - "5173:5173"
    depends_on:
      - api

networks:
  default:
    name: analista_network
